
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vendora_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.17.2"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"  # Выделяем 1 ГБ памяти для JVM
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    networks:
      - elastic-net

  kibana:
    image: "docker.elastic.co/kibana/kibana:8.17.2"
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - "5601:5601"
    depends_on:
      - es01
    networks:
      - elastic-net

  keycloak:
    image: keycloak-custom
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  es-data:
    driver: local
  pgdata:
  keycloak_data:

networks:
  elastic-net:
    driver: bridge

